- hosts: k8s_nodes
  become: true
  tasks:
    - name: Copy Kubernetes manifests
      copy:
        src: ../k8s/
        dest: /home/ubuntu/k8s/

    - name: Apply Kubernetes manifests
      command: kubectl apply -f /home/ubuntu/k8s/
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
